# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Paul\Documents\projects\Adafruit_Python_PCA9685\ui\slider_gui.ui'
#
# Created: Tue Dec 31 13:00:27 2019
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1647, 380)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.horizontalLayout_8.addWidget(self.groupBox_2)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.slider_table = QtGui.QSlider(self.groupBox)
        self.slider_table.setMinimum(170)
        self.slider_table.setMaximum(580)
        self.slider_table.setOrientation(QtCore.Qt.Horizontal)
        self.slider_table.setInvertedAppearance(False)
        self.slider_table.setInvertedControls(False)
        self.slider_table.setTickPosition(QtGui.QSlider.TicksAbove)
        self.slider_table.setTickInterval(1)
        self.slider_table.setObjectName("slider_table")
        self.horizontalLayout_6.addWidget(self.slider_table)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.slider_arm = QtGui.QSlider(self.groupBox)
        self.slider_arm.setMinimum(170)
        self.slider_arm.setMaximum(580)
        self.slider_arm.setOrientation(QtCore.Qt.Horizontal)
        self.slider_arm.setInvertedAppearance(False)
        self.slider_arm.setInvertedControls(False)
        self.slider_arm.setTickPosition(QtGui.QSlider.TicksAbove)
        self.slider_arm.setTickInterval(1)
        self.slider_arm.setObjectName("slider_arm")
        self.horizontalLayout_5.addWidget(self.slider_arm)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.slider_elbow = QtGui.QSlider(self.groupBox)
        self.slider_elbow.setMinimum(170)
        self.slider_elbow.setMaximum(580)
        self.slider_elbow.setOrientation(QtCore.Qt.Horizontal)
        self.slider_elbow.setInvertedAppearance(False)
        self.slider_elbow.setInvertedControls(False)
        self.slider_elbow.setTickPosition(QtGui.QSlider.TicksAbove)
        self.slider_elbow.setTickInterval(1)
        self.slider_elbow.setObjectName("slider_elbow")
        self.horizontalLayout_4.addWidget(self.slider_elbow)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.slider_forearm = QtGui.QSlider(self.groupBox)
        self.slider_forearm.setMinimum(170)
        self.slider_forearm.setMaximum(580)
        self.slider_forearm.setOrientation(QtCore.Qt.Horizontal)
        self.slider_forearm.setInvertedAppearance(False)
        self.slider_forearm.setInvertedControls(False)
        self.slider_forearm.setTickPosition(QtGui.QSlider.TicksAbove)
        self.slider_forearm.setTickInterval(1)
        self.slider_forearm.setObjectName("slider_forearm")
        self.horizontalLayout_3.addWidget(self.slider_forearm)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.slider_wrist_spin = QtGui.QSlider(self.groupBox)
        self.slider_wrist_spin.setMinimum(170)
        self.slider_wrist_spin.setMaximum(580)
        self.slider_wrist_spin.setOrientation(QtCore.Qt.Horizontal)
        self.slider_wrist_spin.setInvertedAppearance(False)
        self.slider_wrist_spin.setInvertedControls(False)
        self.slider_wrist_spin.setTickPosition(QtGui.QSlider.TicksAbove)
        self.slider_wrist_spin.setTickInterval(1)
        self.slider_wrist_spin.setObjectName("slider_wrist_spin")
        self.horizontalLayout_2.addWidget(self.slider_wrist_spin)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.slider_wrist_spin_2 = QtGui.QSlider(self.groupBox)
        self.slider_wrist_spin_2.setMinimum(170)
        self.slider_wrist_spin_2.setMaximum(580)
        self.slider_wrist_spin_2.setOrientation(QtCore.Qt.Horizontal)
        self.slider_wrist_spin_2.setInvertedAppearance(False)
        self.slider_wrist_spin_2.setInvertedControls(False)
        self.slider_wrist_spin_2.setTickPosition(QtGui.QSlider.TicksAbove)
        self.slider_wrist_spin_2.setTickInterval(1)
        self.slider_wrist_spin_2.setObjectName("slider_wrist_spin_2")
        self.horizontalLayout.addWidget(self.slider_wrist_spin_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_8.addWidget(self.groupBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1647, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Table", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Arm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Elbow", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Forearm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Wrist Tilt", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Wrist Spin", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Butt stuff", None, QtGui.QApplication.UnicodeUTF8))

